# -*- coding: utf-8 -*-
"""Project3 IMDB movies Rating Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ida8A3iENqHBHc-2XVWRo8LkahU020le
"""

import pandas as pd

movies = pd.read_csv(r'/content/drive/MyDrive/movies.csv')

movies

movies.head()

movies.head(10)

movies.shape

type(movies)

tags = pd.read_csv(r'/content/drive/MyDrive/tags,csv.csv')

tags

tags.head()

tags.shape

del tags['timestamp']

tags

tags.shape

ratings = pd.read_csv(r'/content/drive/MyDrive/ratings.csv')

ratings

ratings.shape

ratings.head()

del ratings['timestamp']

ratings

ratings.shape

row_0 = tags.iloc[0]
type(row_0)

print(row_0)

row_0.index

row_0['userId']

'rating' in row_0

row_0.name

row_0 = row_0.rename('firstrow')
row_0.name

"""**DATA FRAMES**"""

tags.head()

tags.index

tags.columns

tags.iloc[[0,11,500]]

"""**DESCRIPTIVE STATISTICS**"""

ratings['rating'].describe()

ratings.describe()

ratings['rating'].mean()

ratings.mean()

ratings['rating'].min()

ratings['rating'].max()

ratings['rating'].std()

ratings['rating'].mode()

ratings.mode()

ratings.corr()

filter1 = ratings['rating']>10
print(filter1)
filter1.any()

filter2 = ratings['rating']>0
filter2.all()

"""**DATA CLEANING , HANDLING MISSING VALUES**"""

movies.shape

movies.isnull().any().any()

ratings.shape

ratings.isnull().any().any()

tags.shape

tags.isnull().any().any()

tags = tags.dropna()

tags.isnull().any().any()

tags.shape

"""**DATA VISUALIZATION**"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

ratings.hist(column='rating',figsize=(10,5))

ratings.boxplot(column='rating',figsize = (10,5))

"""**SLICING OUT COLUMNS**"""

tags['tag'].head()

movies[['title','genres']].head()

ratings[-10:]

tag_counts = tags['tag'].value_counts()
tag_counts[-10:]